/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.android.AndroidDriver;
import java.io.File;
import java.net.URL;
import java.nio.charset.Charset;
import java.time.Duration;

import org.apache.commons.io.*;

public class DemoTest {
 
    @Test
    public void testAppiumInvocation() throws Exception {
        File file = new File("C:\\Users\\E010767\\poc_pavan\\webdriverio_component1\\file.json");
        String jsonContent = FileUtils.readFileToString(file, Charset.defaultCharset());
        JsonElement jsonElement = JsonParser.parseString(jsonContent);
        JsonObject json = jsonElement.getAsJsonObject();
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("appium:platformName", "Android");
        caps.setCapability("appium:automationName", "UIAutomator2");
        caps.setCapability("appium:app", "C:\\Users\\E010767\\poc_pavan\\java_appium_component2\\android.wdio.native.app.v1.0.8.apk");
        caps.setCapability("appium:deviceName", "emulator-5554");
        caps.setCapability("appium:appWaitDuration", 60000);
        AndroidDriver driver = new AndroidDriver(new URL("http://localhost:4723"),caps);
        Thread.sleep(20000);
        WebElement logiIcon = waitFor(driver.findElement(AppiumBy.xpath("//android.widget.View[@content-desc=\"Login\"]")), driver);
        WebElement emailTextBox = waitFor(driver.findElement(AppiumBy.accessibilityId("input-email")), driver);
        WebElement passwordTextBox = waitFor(driver.findElement(AppiumBy.accessibilityId("input-password")), driver);
        WebElement loginButton = waitFor(driver.findElement(AppiumBy.xpath("//android.view.ViewGroup[@content-desc=\"button-LOGIN\"]/android.view.ViewGroup")), driver);
        logiIcon.click();
        Thread.sleep(5000);
        emailTextBox.sendKeys(json.get("username").getAsString());
        passwordTextBox.sendKeys(json.get("password").getAsString());
        loginButton.click();
        Thread.sleep(10000);
        driver.close();
    }

    private static WebElement waitFor(WebElement elemeent, WebDriver driver) throws Exception {
        WebDriverWait w = new WebDriverWait(driver, Duration.ofSeconds(600));
        return w.pollingEvery(Duration.ofSeconds(50)).until(ExpectedConditions.elementToBeClickable(elemeent));
    }
}
