/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.net.URL;
import java.nio.charset.Charset;
import java.time.Duration;

import org.apache.commons.io.FileUtils;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.android.AndroidDriver;

public class DemoTest {
 
    @Test
    public void testAppiumInvocation() throws Exception {
        File file = new File("C:\\Users\\E010767\\poc_pavan\\webdriverio_component1\\file.json");
        String jsonContent = FileUtils.readFileToString(file, Charset.defaultCharset());
        JsonElement jsonElement = JsonParser.parseString(jsonContent);
        JsonObject json = jsonElement.getAsJsonObject();
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("appium:platformName", "Android");
        caps.setCapability("appium:automationName", "UIAutomator2");
        caps.setCapability("appium:app", "C:\\Users\\E010767\\poc_pavan\\java_appium_component2\\android.wdio.native.app.v1.0.8.apk");
        caps.setCapability("appium:deviceName", "emulator-5554");
        caps.setCapability("appium:appWaitDuration", 60000);
        AndroidDriver driver = new AndroidDriver(new URL("http://localhost:4723"),caps);
        Thread.sleep(20000);
        WebElement logiIcon = waitFor(AppiumBy.accessibilityId("Login"), driver);
        logiIcon.click();
        WebElement emailTextBox = waitFor(AppiumBy.accessibilityId("input-email"), driver);
        emailTextBox.click();
        emailTextBox.sendKeys(json.get("username").getAsString());
        WebElement passwordTextBox = waitFor(AppiumBy.accessibilityId("input-password"), driver);
        passwordTextBox.sendKeys(json.get("password").getAsString());
        WebElement loginButton = waitFor(AppiumBy.xpath("//android.view.ViewGroup[@content-desc=\"button-LOGIN\"]/android.view.ViewGroup"), driver);
        
        // Thread.sleep(5000);
       
        // passwordTextBox.sendKeys(json.get("password").getAsString());
        loginButton.click();
        Thread.sleep(10000);
        // d.close();
    }

    private static WebElement waitFor(By elemeent, WebDriver driver) throws Exception {
        WebDriverWait w = new WebDriverWait(driver, Duration.ofSeconds(600));
        w.pollingEvery(Duration.ofSeconds(50)).until(ExpectedConditions.elementToBeClickable(elemeent));
        return driver.findElement(elemeent);
    }
}
